from sentence_transformers import SentenceTransformer

class JobTitles:

    titles = [
        # Management & Leadership
        "Manager",
        "Project Manager",
        "Program Manager",
        "Product Manager",
        "Team Lead",
        "Director",
        "Operations Manager",
        "HR Manager",
        "Finance Manager",
        "Marketing Manager",
        "Sales Manager",
        "General Manager",
        "Chief Executive Officer",
        "CEO",
        "Chief Operating Officer",
        "COO",
        "Chief Financial Officer",
        "CFO",
        "Chief Technology Officer",
        "CTO",
        "Chief Marketing Officer",
        "CMO",
        "Branch Manager",
        "Assistant Manager",
        "Deputy Manager",
        "Regional Manager",
        "Area Manager",

        # Technical / IT
        "Software Engineer",
        "Senior Software Engineer",
        "Junior Software Engineer",
        "Developer",
        "Full Stack Developer",
        "Frontend Developer",
        "Backend Developer",
        "Mobile Developer",
        "Web Developer",
        "QA Engineer",
        "Quality Assurance Engineer",
        "DevOps Engineer",
        "System Administrator",
        "Network Engineer",
        "Data Analyst",
        "Data Scientist",
        "Machine Learning Engineer",
        "AI Engineer",
        "Cloud Engineer",
        "Database Administrator",
        "IT Support Specialist",
        "IT Manager",
        "Cybersecurity Analyst",
        "Security Engineer",
        "UX Designer",
        "UI Designer",
        "UI/UX Designer",
        "Graphic Designer",
        "Technical Lead",
        "Software Architect",
        "Solution Architect",
        "Product Owner",
        "Scrum Master",

        # Business & Administration
        "Business Analyst",
        "Consultant",
        "Strategy Consultant",
        "Operations Analyst",
        "Executive Assistant",
        "Administrative Assistant",
        "Office Manager",
        "Coordinator",
        "Supervisor",
        "Specialist",
        "Project Coordinator",
        "Program Coordinator",
        "Business Development Manager",
        "Account Manager",
        "Account Executive",
        "Client Relationship Manager",
        "Client Services Manager",
        "Customer Success Manager",
        "Operations Coordinator",

        # Finance & Accounting
        "Accountant",
        "Senior Accountant",
        "Financial Analyst",
        "Senior Financial Analyst",
        "Auditor",
        "Internal Auditor",
        "External Auditor",
        "Bookkeeper",
        "Controller",
        "Treasurer",
        "Payroll Specialist",
        "Finance Officer",
        "Investment Analyst",
        "Tax Consultant",
        "Tax Manager",
        "Budget Analyst",
        "Credit Analyst",
        "Risk Manager",

        # Sales & Marketing
        "Sales Representative",
        "Sales Executive",
        "Sales Associate",
        "Marketing Specialist",
        "Marketing Coordinator",
        "Digital Marketing Specialist",
        "SEO Specialist",
        "Social Media Manager",
        "Brand Manager",
        "Content Writer",
        "Copywriter",
        "Advertising Manager",
        "Business Development Executive",
        "Account Executive",
        "Regional Sales Manager",
        "Sales Director",
        "Marketing Director",
        "Product Marketing Manager",
        "Email Marketing Specialist",
        "Affiliate Manager",

        # Human Resources
        "HR Specialist",
        "HR Coordinator",
        "HR Manager",
        "Recruiter",
        "Talent Acquisition Specialist",
        "Training Coordinator",
        "Learning and Development Manager",
        "HR Generalist",
        "HR Business Partner",
        "Compensation and Benefits Manager",
        "Employee Relations Specialist",
        "Organizational Development Manager",
        "HR Director",

        # Operations & Logistics
        "Operations Manager",
        "Operations Coordinator",
        "Logistics Manager",
        "Supply Chain Manager",
        "Inventory Specialist",
        "Warehouse Manager",
        "Procurement Specialist",
        "Purchasing Manager",
        "Fleet Manager",
        "Transportation Coordinator",
        "Shipping and Receiving Clerk",
        "Facility Manager",
        "Plant Manager",
        "Production Manager",
        "Manufacturing Supervisor",
        "Operations Analyst",

        # Healthcare
        "Nurse",
        "Registered Nurse",
        "Licensed Practical Nurse",
        "Doctor",
        "Physician",
        "Medical Assistant",
        "Pharmacist",
        "Therapist",
        "Physical Therapist",
        "Occupational Therapist",
        "Medical Technologist",
        "Lab Technician",
        "Healthcare Administrator",
        "Clinical Coordinator",
        "Surgeon",
        "Dentist",

        # Education
        "Teacher",
        "Teaching Assistant",
        "Lecturer",
        "Instructor",
        "Professor",
        "Assistant Professor",
        "Tutor",
        "Trainer",
        "Education Coordinator",
        "Academic Advisor",
        "Research Associate",
        "Research Assistant",
        "Principal",
        "Vice Principal",
        "Dean",

        # Creative / Media
        "Graphic Designer",
        "Visual Designer",
        "Art Director",
        "Creative Director",
        "Animator",
        "Video Editor",
        "Photographer",
        "Illustrator",
        "Content Creator",
        "Copywriter",
        "Writer",
        "Editor",
        "Producer",
        "Director of Photography",
        "Social Media Content Creator",

        # Customer Service / Support
        "Customer Service Representative",
        "Customer Support Specialist",
        "Support Agent",
        "Call Center Agent",
        "Service Manager",
        "Client Support Specialist",
        "Help Desk Analyst",
        "Technical Support Engineer",
        "Customer Success Specialist",
        "Account Support Manager",
        "Receptionist",
        "Front Desk Officer",

        "Freelancer"
    ]

    def __init__(self, encoder):
        self.model = SentenceTransformer(encoder, trust_remote_code=True)

        self._encodes = self.model.encode(self.titles)

    def find_title(self, title: str, threshold = 0.85) -> str:
        encoded = self.model.encode([title])

        best = self.model.similarity(encoded,self._encodes)[0].topk(1)

        if best.values.item() >= threshold:
            return self.titles[best.indices.item()]

        return ""
