class SkillsInfo(object):

    skills = [
        "3D Modeling",
        "A/B Testing",
        "A/B Testing for Product",
        "Active Listening",
        "Adaptability",
        "Adobe Illustrator",
        "Adobe Photoshop",
        "Adobe Premiere Pro",
        "Advanced Excel",
        "Agile Development",
        "Agile Methodologies",
        "AI Ethics",
        "AI Governance",
        "AI Model Evaluation",
        "AI Product Management",
        "AI Safety",
        "Android Development",
        "Anomaly Detection",
        "API Development",
        "API Design",
        "Application Security",
        "Attention to Detail",
        "AWS",
        "Azure",
        "Back-end Development",
        "Bash Scripting",
        "Batch Inference",
        "Big Data",
        "Blockchain",
        "Brand Strategy",
        "Branding",
        "Bug Tracking",
        "Business Acumen",
        "Business Intelligence",
        "CAD",
        "Calendar Management",
        "Change Management",
        "Chroma",
        "CI/CD",
        "CI/CD Pipelines",
        "CircleCI",
        "Client Interaction",
        "Cloud Architecture",
        "Cloud Computing",
        "Cloud Cost Optimization",
        "Cloud Databases",
        "Cloud Security",
        "CloudFormation",
        "Closing Deals",
        "Coaching",
        "Collaboration",
        "Computer Vision",
        "Conflict Resolution",
        "Content Creation",
        "Content Marketing",
        "Contract Negotiation",
        "Copywriting",
        "Creativity",
        "Critical Thinking",
        "Cross-Browser Compatibility",
        "Cross-functional Communication",
        "CRM Management",
        "CRM Usage",
        "CSS",
        "Customer Service",
        "Customer Success",
        "Cybersecurity",
        "Cypress",
        "Dart",
        "Data Analysis",
        "Data Architecture",
        "Data Engineering",
        "Data Entry",
        "Data Labeling",
        "Data Lakes",
        "Data Mining",
        "Data Modeling",
        "Data Pipelines",
        "Data Structures",
        "Data Structures & Algorithms",
        "Data Versioning",
        "Data Visualization",
        "Data Warehousing",
        "Dashboarding",
        "Decision Making",
        "Deep Learning",
        "Delegation",
        "Delta Lake",
        "Design Patterns",
        "DevOps",
        "Django",
        "Distributed Systems",
        "Docker",
        "Electrical Systems",
        "Email Management",
        "Email Marketing",
        "Embedding Models",
        "Encryption",
        "Emotional Intelligence",
        "Engineering Design",
        "ETL Development",
        "ETL Pipelines",
        "Event-driven Architecture",
        "Excel",
        "Express",
        "FAISS",
        "Feature Engineering",
        "Feature Stores",
        "Figma",
        "Financial Analysis",
        "Financial Literacy",
        "Flask",
        "Flexibility",
        "Flutter",
        "Forecasting",
        "Forecasting Models",
        "Front-end Development",
        "Functional Programming",
        "GCP ",
        "Generative AI",
        "Git",
        "GitHub",
        "GitHub Actions",
        "GitLab",
        "GitLab CI",
        "Go ",
        "Google Ads",
        "Google Analytics",
        "Google Cloud Platform",
        "Grafana",
        "Graph Databases",
        "GraphQL",
        "Graphic Design",
        "gRPC",
        "Help Desk Support",
        "High Availability Systems",
        "Hadoop",
        "HTML",
        "Hugging Face Transformers",
        "Hypothesis Testing",
        "Identity & Access Management",
        "Image Generation",
        "Illustration",
        "Incident Response",
        "Industrial Engineering",
        "Information Security",
        "Infrastructure as Code",
        "Innovation",
        "Integration Testing",
        "Interpersonal Skills",
        "IoT Development",
        "iOS Development",
        "Istio",
        "Java",
        "JavaScript",
        "JAX",
        "Jenkins",
        "Jira",
        "Jupyter Notebooks",
        "JUnit",
        "Kanban",
        "Keras",
        "Knowledge Graphs",
        "Kotlin",
        "Kubernetes",
        "Laravel",
        "Large Language Models",
        "Leadership",
        "Lean Methodology",
        "Legal Research",
        "Linux Administration",
        "Load Balancing",
        "Looker",
        "Machine Learning",
        "Managing Stakeholders",
        "Manufacturing Processes",
        "Manual Testing",
        "Market Research",
        "Marketing Analytics",
        "MATLAB",
        "Mechanical Engineering",
        "Meta Ads",
        "Miro",
        "Milvus",
        "ML Pipelines",
        "ML Experiment Tracking",
        "MLflow",
        "Mobile Testing",
        "Mobile UI/UX",
        "Model Deployment",
        "Model Fine-Tuning",
        "Model Monitoring",
        "Model Optimization",
        "Model Serving",
        "MongoDB",
        "Motion Graphics",
        "Multimodal AI",
        "MySQL",
        "Natural Language Processing",
        "NLP",
        "Negotiation",
        "Network Administration",
        "Network Security",
        "Neo4j",
        "Next.js",
        "NoSQL",
        "Node.js",
        "Object-Oriented Programming",
        "ONNX",
        "OpenAI API",
        "OpenCV",
        "Operational Excellence",
        "Organization",
        "Penetration Testing",
        "Performance Management",
        "Performance Optimization",
        "Pipeline Management",
        "Pinecone",
        "Playwright",
        "PostgreSQL",
        "Power BI",
        "Predictive Analytics",
        "Predictive Modeling",
        "Presentation Skills",
        "Problem Solving",
        "Procurement",
        "Product Lifecycle Management",
        "Product Management",
        "Product Roadmapping",
        "Product Strategy",
        "Program Management",
        "Project Management",
        "Prometheus",
        "Prompt Engineering",
        "Prototyping",
        "Python",
        "Python for Data",
        "PyTorch",
        "Quality Assurance",
        "Quality Control",
        "Quantum Computing Basics",
        "Real Estate Management",
        "Real-time Inference",
        "Real-time Processing",
        "Record Keeping",
        "Redis",
        "Regression Testing",
        "Reinforcement Learning",
        "Reporting",
        "Requirement Analysis",
        "Resilience",
        "REST APIs",
        "Responsive Web Design",
        "Retrieval-Augmented Generation",
        "RAG",
        "Risk Assessment",
        "Risk Management",
        "Ruby",
        "Rust",
        "S3",
        "Sales",
        "Salesforce",
        "SASS",
        "Scheduling",
        "Scikit-learn",
        "Scrum",
        "Security Compliance",
        "Security Governance",
        "Security Policies",
        "Selenium",
        "Serverless Architecture",
        "Shell Scripting",
        "Six Sigma",
        "Smart Contracts",
        "Snowflake",
        "Social Media Management",
        "Software Testing",
        "Speech Recognition",
        "SQL",
        "SQL Programming",
        "Statistics",
        "Stress Management",
        "Swift",
        "System Administration",
        "System Design",
        "Tableau",
        "Tax Preparation",
        "Team Leadership",
        "Teamwork",
        "TensorFlow",
        "Terraform",
        "Test Automation",
        "Test Planning",
        "Test-Driven Development",
        "Threat Modeling",
        "Time Management",
        "Travel Coordination",
        "Troubleshooting",
        "TypeScript",
        "UI/UX",
        "Unit Testing",
        "User Acceptance Testing",
        "User Research",
        "Version Control",
        "Video Editing",
        "Vulnerability Assessment",
        "Vue.js",
        "Weaviate",
        "Wireframing",
        "Work Ethic",
        "Written Communication",
        "Zero Trust Security",

        # Non Tech
        "Accountability",
        "Active Learning",
        "Active Participation",
        "Adaptability to Change",
        "Ambition",
        "Approachability",
        "Assertiveness",
        "Authenticity",
        "Autonomy",
        "Brainstorming",
        "Brand Storytelling",
        "Business Storytelling",
        "Calm Under Pressure",
        "Career Ownership",
        "Change Readiness",
        "Coaching Mindset",
        "Cognitive Flexibility",
        "Collaborative Problem Solving",
        "Commitment",
        "Compassion",
        "Complex Problem Solving",
        "Confidentiality",
        "Consensus Building",
        "Constructive Conflict Handling",
        "Constructive Criticism",
        "Consultative Approach",
        "Continuous Learning",
        "Courage",
        "Cultural Adaptability",
        "Cultural Awareness",
        "Cultural Competence",
        "Cultural Sensitivity",
        "Customer Empathy",
        "Decision Facilitation",
        "De-escalation Skills",
        "Dependability",
        "Design Thinking Mindset",
        "Detail Orientation",
        "Diplomacy",
        "Discretion",
        "Diversity & Inclusion Awareness",
        "Emotional Control",
        "Empathy",
        "Entrepreneurial Thinking",
        "Ethical Decision Making",
        "Ethical Judgment",
        "Etiquette",
        "Facilitation Skills",
        "Follow-through",
        "Goal Setting",
        "Growth Mindset",
        "Handling Ambiguity",
        "Handling Pressure",
        "Honesty",
        "Hospitality Mindset",
        "Impartiality",
        "Inclusiveness",
        "Independent Thinking",
        "Influence Without Authority",
        "Initiative",
        "Integrity",
        "Judgment",
        "Learning Agility",
        "Listening Without Bias",
        "Logical Reasoning",
        "Managing Expectations",
        "Managing Up",
        "Mediation",
        "Meeting Facilitation",
        "Mentoring",
        "Mindfulness",
        "Motivation",
        "Negotiation Mindset",
        "Non-verbal Communication",
        "Open-mindedness",
        "Optimism",
        "Organizational Awareness",
        "Ownership Mindset",
        "Patience",
        "People-Centric Mindset",
        "Performance Coaching",
        "Personal Accountability",
        "Personal Branding",
        "Perspective Taking",
        "Persuasion",
        "Positive Attitude",
        "Positive Reinforcement",
        "Presentation Confidence",
        "Prioritizing Conflicts",
        "Professional Integrity",
        "Professionalism",
        "Project Coordination",
        "Proposal Writing",
        "Public Relations Awareness",
        "Relationship Building",
        "Reliability",
        "Resourcefulness",
        "Respectfulness",
        "Responsiveness",
        "Results-Driven Mindset",
        "Self-Awareness",
        "Self-Confidence",
        "Self-Control",
        "Self-Discipline",
        "Self-Improvement",
        "Self-Learning",
        "Self-Motivation",
        "Self-Management",
        "Sense of Ownership",
        "Service Mindset",
        "Situational Adaptability",
        "Situational Awareness",
        "Social Awareness",
        "Social Perceptiveness",
        "Solution-Oriented Thinking",
        "Storytelling",
        "Stress Tolerance",
        "Supportiveness",
        "Sustainability Awareness",
        "Systems Thinking",
        "Team Building",
        "Team Coordination",
        "Team Motivation",
        "Team Orientation",
        "Tolerance",
        "Trust Building",
        "Trustworthiness",
        "Verbal Reasoning",
        "Visual Communication",
        "Well-being Management",
        "Workplace Empathy",
        "Workplace Etiquette",
        "Workplace Inclusivity",
        "Workplace Integrity",
        "Workplace Professionalism",
        "Workplace Resilience",

        # Additional uncommon but relevant non-technical skills
        "Account Relationship Skills",
        "Adaptability Coaching",
        "Attentiveness",
        "Balancing Priorities",
        "Belonging Facilitation",
        "Boundary Setting",
        "Business Etiquette",
        "Caring Leadership",
        "Clarity in Communication",
        "Commitment to Excellence",
        "Community Engagement",
        "Conflict Mediation",
        "Constructive Debate",
        "Crisis Communication",
        "Crisis Management Soft Skills",
        "Diplomatic Communication",
        "Employee Engagement",
        "Ethical Communication",
        "Fairness",
        "Fearlessness",
        "Followership",
        "Future-Oriented Thinking",
        "Goal Orientation",
        "Human-Centered Thinking",
        "Intercultural Competence",
        "Interdisciplinary Collaboration",
        "Leadership Presence",
        "Learning Mindset",
        "Life-Long Learning",
        "Listening Empathy",
        "Mindful Decision Making",
        "Multicultural Awareness",
        "Narrative Framing",
        "Needs Assessment",
        "Nonviolent Communication",
        "Organizational Storytelling",
        "Peer Coaching",
        "Performance Feedback",
        "Personal Effectiveness",
        "Personal Responsibility",
        "Prioritization Under Pressure",
        "Psychological Safety Building",
        "Purpose-Driven Thinking",
        "Receptiveness",
        "Reflective Thinking",
        "Relationship Management",
        "Reliable Judgment",
        "Respect for Diversity",
        "Service Orientation",
        "Shared Leadership",
        "Situational Communication",
        "Social Responsibility",
        "Stakeholder Empathy",
        "Team Trust Development",
        "Time Awareness",
        "Unity Building",

        # --- Engineering & Manufacturing ---
        "Mechanical Engineering",
        "Electrical Engineering",
        "Civil Engineering",
        "Structural Engineering",
        "Chemical Engineering",
        "Industrial Engineering",
        "Aerospace Engineering",
        "Automotive Engineering",
        "Manufacturing Engineering",
        "Robotics (Mechanical/Hardware)",
        "Mechatronics",
        "HVAC Systems",
        "Pneumatics",
        "Hydraulics",
        "Welding",
        "Metal Fabrication",
        "Machining",
        "CNC Operation",
        "CNC Programming (Machine tool specific)",
        "Quality Engineering",
        "Failure Analysis",
        "Root Cause Analysis (Manufacturing)",
        "Technical Drawing",
        "Blueprint Reading",
        "GD&T (Geometric Dimensioning & Tolerancing)",
        "CAD Modeling",
        "3D Printing",
        "Reverse Engineering",
        "Injection Molding",
        "Casting Processes",
        "Lean Manufacturing",
        "Six Sigma (non-software)",
        "Kaizen",
        "TPM (Total Productive Maintenance)",
        "Process Optimization",
        "SPC (Statistical Process Control)",
        "Fabrication Techniques",
        "Industrial Safety",
        "Equipment Calibration",
        "PLC Operation (not programming)",
        "Automation Equipment Setup",

        # --- Construction & Trades ---
        "Construction Management",
        "Carpentry",
        "Plumbing",
        "Electrical Wiring",
        "Masonry",
        "Roofing",
        "Blueprint Interpretation",
        "Building Inspection",
        "OSHA Compliance",
        "Worksite Safety",
        "Concrete Work",
        "Surveying",
        "GIS Mapping (non-software heavy)",
        "AutoCAD Drafting",
        "Landscaping Design",
        "Interior Renovation",
        "Contractor Management",

        # --- Scientific & Laboratory ---
        "Laboratory Testing",
        "Microscopy",
        "Spectroscopy",
        "Chromatography",
        "PCR Testing",
        "DNA Extraction",
        "Cell Culture",
        "Microbiology Techniques",
        "Biochemistry Assays",
        "Environmental Testing",
        "Water Quality Testing",
        "Material Testing",
        "Chemical Safety",
        "Lab Equipment Calibration",
        "Lab Sample Preparation",
        "Histology",
        "Toxicology Testing",
        "Food Safety Testing",
        "Quality Control (Laboratory)",
        "Clinical Diagnostics",

        # --- Healthcare & Medical ---
        "Patient Assessment",
        "Patient Triage",
        "Vital Signs Monitoring",
        "Medical Imaging (X-ray, MRI operation)",
        "Radiology Tech Skills",
        "Ultrasound Operation",
        "EKG/ECG Operation",
        "Pharmacy Dispensing",
        "Medication Administration",
        "Wound Care",
        "Phlebotomy",
        "IV Insertion",
        "Basic Life Support (BLS)",
        "Advanced Cardiovascular Life Support (ACLS)",
        "CPR Certification",
        "Medical Coding",
        "Clinical Documentation",
        "Infection Control",
        "Sterilization Techniques",
        "Respiratory Therapy",
        "Audiology Testing",
        "Dental Assisting",
        "Optometry Equipment Use",

        # --- Supply Chain, Logistics & Operations ---
        "Supply Chain Planning",
        "Inventory Control",
        "Procurement Operations",
        "Demand Forecasting (non-software heavy)",
        "Warehouse Management",
        "Logistics Coordination",
        "Freight Handling",
        "Fleet Management",
        "Forklift Operation",
        "Heavy Machinery Operation",
        "Lean Warehousing",
        "Route Planning",
        "Import/Export Compliance",
        "Customs Documentation",
        "Vendor Coordination",
        "Production Scheduling",

        # --- Technical Sales / Product / Hardware ---
        "Technical Product Demonstration",
        "Hardware Troubleshooting",
        "Electrical Equipment Testing",
        "Physical Prototyping",
        "Sensor Calibration",
        "Device Assembly",
        "Product Quality Testing",
        "Material Selection",
        "Industrial Design Principles",
        "Technical Writing",
        "Regulatory Compliance (non-software)",

        # --- Energy & Utilities ---
        "Power Distribution Systems",
        "Electrical Load Analysis",
        "Grid Management",
        "Battery Systems Maintenance",
        "Solar Energy Installation",
        "Solar Panel Testing",
        "Wind Turbine Maintenance",
        "Oil & Gas Drilling Operations",
        "Pipeline Inspection",
        "Water Treatment Systems",
        "Boiler Operation",
        "Pump Systems",
        "Turbine Operation",

        # --- Automotive & Transportation ---
        "Automotive Diagnostics",
        "Engine Repair",
        "Transmission Repair",
        "Brake Systems",
        "Suspension Systems",
        "Vehicle Electrical Systems",
        "Auto Body Repair",
        "Tire Mounting & Balancing",
        "Fleet Maintenance",
        "Aviation Maintenance",
        "Aircraft Inspection",
        "Marine Systems Maintenance",

        # --- Environment, Safety & Compliance ---
        "Environmental Monitoring",
        "Hazardous Waste Handling",
        "EPA Compliance",
        "Fire Safety Systems",
        "Emergency Response Procedures",
        "Risk Assessment (non-software)",
        "ISO Standards Compliance",
        "Safety Auditing",
        "Ergonomics Analysis",
        "Industrial Hygiene",
        "Air Quality Measurement",
        "Radiation Safety",

        # --- Agriculture, Food & Natural Resources ---
        "Agricultural Equipment Operation",
        "Soil Analysis",
        "Crop Management",
        "Irrigation Systems",
        "Food Processing",
        "Food Quality Assurance",
        "Livestock Handling",
        "Veterinary Assistance",
        "Farm Machinery Maintenance",

        # --- Media, Audio & Creative Technical ---
        "Audio Engineering",
        "Sound Mixing",
        "Camera Operation",
        "Lighting Setup",
        "Studio Equipment Setup",
        "Production Design",
        "Stage Management",
        "Film Editing (hardware operations)",
        "Color Grading (technical)",

        # --- Other Hard Technical Skills ---
        "Statistics (non-programming application)",
        "Mathematical Modeling",
        "Project Estimation",
        "Technical Auditing",
        "Technical Compliance",
        "Document Control",
        "Quality Documentation",
        "Blueprint Verification",
        "Inspection Techniques",
        "Packaging Engineering",
        "Facility Management",
        "Asset Management",
        "Maintenance Scheduling"
    ]



    def find_in_text(self, text: list[str]) -> list[str]:
        data = " ".join(text).lower()
        result = []
        for skill in self.skills:
            if skill.lower() in data:
                result.append(skill)

        return result